# Generated by Django 3.2.16 on 2024-07-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240701_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['following__username', 'user__username']},
        ),
    ]
